### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by ValAug** [LiveEngage-Examples/LiveEngage-Engagement-History-API#5] opened 2020-05-08 18:29 UTC
Hello quick question. 

Is this a standard key name or was costumed according to your project because I am getting the following error.
```
 for record in engHistoryResults['interactionHistoryRecords']:
KeyError: 'interactionHistoryRecords'
```
Please advise and thank you for your help

**Comment by scottwestover** [comment] 2020-05-08 19:40
Closing. This issue is a duplicate of https://github.com/LiveEngage-Examples/LiveEngage-Engagement-History-API/issues/6

**Closed as completed by scottwestover** 2020-05-08 19:40 UTC
